"""add index user and client

Revision ID: ab3b4e98c553
Revises:
Create Date: 2026-02-01 10:06:49.475458

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "ab3b4e98c553"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
