"""add index

Revision ID: f6fb6fd94090
Revises: ab3b4e98c553
Create Date: 2026-02-01 19:25:47.053890

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f6fb6fd94090"
down_revision: str | Sequence[str] | None = "ab3b4e98c553"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("ix_cases_case_number_btree", "cases", ["case_number"], unique=False)
    op.create_index("ix_cases_number_btree", "cases", ["number"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_cases_number_btree", table_name="cases")
    op.drop_index("ix_cases_case_number_btree", table_name="cases")
    # ### end Alembic commands ###
